### ISSUE TITLE
UnicodeDecodeError with files with utf-8

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#58]
Hi,

I am running this with pre-commit (in the process of setting it up) and encountering issues where the file i'm running it on has a "# -- coding: utf-8 --" up the top, but in the importanize script it uses with '`ource.read_text()` in `run_importanize_on_file` which results in the platform default encoding used and a UnicodeDecodeError.

I take it this isn't completely unicode safe yet?

**Comment by miki725** [comment]
can you paste full traceback?

**Comment by commentator8** [comment]
'Error running importanize
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\importanize\__main__.py", line 411, in main
    all_groups += [i for i in run(p, config, args)]
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\importanize\__main__.py", line 411, in <listcomp>
    all_groups += [i for i in run(p, config, args)]
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\importanize\__main__.py", line 332, in run
    for i in run(text, config, args, source):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\importanize\__main__.py", line 308, in run
    path.write_text(organized)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pathlib2\__init__.py", line 1502, in write_text
    return f.write(data)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\encodings\cp1255.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2124-2139: character maps to <undefined>'

**Comment by miki725** [comment]
thanks for the report. Ill add support for PEP 263

**Comment by miki725** [comment]
so working on this in spare time to add full PEP263 support. there is an edge case when printing a file to `stdout` via `importanize --print` or via pipes `cat test.py | importanize`. since my system default encoding is utf-8 Im forcing another one with `PYTHONIOENCODING` env var. if the python source code will contain any characters which terminal will not be able to print it will bomb:

```
❯ echo привет | env PYTHONIOENCODING=ascii python -c 'import sys, click; click.echo(sys.stdin.read())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/miki725/.virtualenvs/importanize/bin/../lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

I thought maybe `click.echo` might be able to handle it but it seems thats not the case. not sure if there are any work arounds to handle these cases.

out of curiosity can you describe your system so I can replicate it a little better?

**Comment by commentator8** [comment]
Im on a windows system with the default encoding cp1255.  If you look here they give an example of what black does.
https://github.com/psf/black/blob/master/black.py#L775

**Comment by miki725** [comment]
have something working. would you be able to test it out? https://github.com/miki725/importanize/pull/60

**Comment by commentator8** [comment]
Looks good, doesn't crash and outputs  when the top line encoding doesn't work with the content. Thanks!
