### ISSUE TITLE
pre-commit fails to run due to importanize

### ISSUE THREAD

**Issue by commentator8** [miki725/importanize#64]
Hi,

I am getting an error that i'm not sure is pre-commit related or importanize (although i suspect both). When i add the following to my pre-commit config i suddenly cant run pre-commit as i get the below error. Only when i add `language_version: python3.8` to the importanize hook does it work. I suspect it is related to the hook you have in the repo that sets the langauge to python3. Any idea?

```
  - repo: https://github.com/miki725/importanize/
    rev: '0.7'
    hooks:
    - id: importanize
      args: [--config=setup.cfg]
      exclude: ^launcher/requirements/
```

The below is from the pre-commit log already pre-formatted.

### version information

```
pre-commit version: 1.20.0
sys.version:
    3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
sys.executable: c:\users\user\appdata\local\programs\python\python38-32\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('c:\\users\\user\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-mvirtualenv', 'C:\\Users\\user\\.cache\\pre-commit\\repo0fr10xh9\\py_env-python3.6', '-p', 'C:\\python36\\python.exe')
return code: 3
expected return code: 0
stdout:
    The path C:\python36\python.exe (from --python=C:\python36\python.exe) does not exist
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\error_handler.py", line 72, in error_handler
    yield
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\main.py", line 344, in main
    return run(args.config, store, args)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\commands\run.py", line 292, in run
    install_hook_envs(hooks, store)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\repository.py", line 220, in install_hook_envs
    hook.install()
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\repository.py", line 97, in install
    lang.install_environment(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\languages\python.py", line 169, in install_environment
    _make_venv(env_dir, python)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\languages\python.py", line 181, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pre_commit\util.py", line 141, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('c:\\users\\user\\appdata\\local\\programs\\python\\python38-32\\python.exe', '-mvirtualenv', 'C:\\Users\\user\\.cache\\pre-commit\\repo0fr10xh9\\py_env-python3.6', '-p', 'C:\\python36\\python.exe')
return code: 3
expected return code: 0
stdout:
    The path C:\python36\python.exe (from --python=C:\python36\python.exe) does not exist
    
stderr: (none)

```

Note that although i have python3.8 installed and it runs it, it tries to make a virtual env with python3.6 due to importanize's language version.

**Comment by miki725** [comment]
0.7 version had 3.6 version hardcoded. Master and next version will simply require 3. https://github.com/miki725/importanize/blob/0.7/.pre-commit-hooks.yaml
